baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Sankaraleengam Alagapan
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

#menu:
#    main:
#        - name: Books
#          url: books/
#          weight: 5 
#        - name: Papers
#          url: papers/
#          weight: 2
#        - name: Courses
#          url: courses/
#          weight: 3
#        - name: Data
#          url: data/
#          weight: 4 
#        - name: Blog
#          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
#          weight: 6

params:
    description: "This website hosts Sankar Alagapan's research, curriculum vitae, and contact information."
    author: Sankar Alagapan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sankaraleengam Alagapan, PhD
          subtitle: "I am a Research Faculty member at Georgia Institute of Technology. I co-direct the Structured Information for Precision Neuroengineering Lab within the School of Electrical and Computer Engineering. I work at the intersection of neurotechnology and psychiatry with the aim of developing brain stimulation therapies for psychiatric disorders. I received my PhD in Biomedical Engineering from the University of Florida. Prior to joining Georgia Tech, I was a post-doctoral research associate at the University of North Carolina at Chapel Hill, working in the Carolina Center for Neurostimulation (spun off from Frohlich Lab). I enjoy photography, travel (to a certain extent) and (re)learning history."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
          #  - name: Papers
          #    url: papers/
            

    socialIcons:
        - name: CV
          url: Alagapan_CV_Mar2025.pdf
        - name: Email
          url: mailto:sankar.alagapan@gatech.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=K0dED3QAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/salagapan
        - name: Twitter
          url: https://x.com/sankar_alagapan
        - name: Bluesky
          url: https://bsky.app/profile/salagapan.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Sankar Alagapan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
